package main

import (
	"encoding/json"
	"fmt"
	"testing"
)

func Test_main(t *testing.T) {

	t.Run("", func(t *testing.T) {
		jsonStr1 := `{"age": 14,"name": "potter", "child":[1,2,3]}`
		a := AutoGenerated{}
		json.Unmarshal([]byte(jsonStr1), &a)
		aa := a.Child
		fmt.Println(aa)
		// jsonStr2 := `{"age": 12,"name": "potter", "child":[3,4,5,7,8,9]}`
		jsonStr2 := `{"age": 12,"name": "potter", "child":[8,9]}`
		json.Unmarshal([]byte(jsonStr2), &a)
		fmt.Println(aa)
		fmt.Println(a)
		fmt.Println("END")
		main2()
	})
}
